### PR TITLE
Feature/update typings

### LINKED ISSUE #85: index.d.ts is not match the API
```ts
export const logger: AppLogger = tracer.colorConsole({ // this is line 44
    format: [
        "[{{timestamp}}] [{{title}}] [{{path}}:{{line}}] [{{processTag}}] [{{message}}]",
        {
            error: "[{{timestamp}}] [{{title}}] [{{path}}:{{line}}] [{{processTag}}] [{{message}}] \n{{stack}}"
        }
    ],
    dateformat: "yyyy-mm-dd HH:MM:ss.l",
    preprocess: function (data) {
        data.path = data.path.replace(config.APPLICATION_CONTEXT_PATH, "");
        data.title = data.title.toUpperCase();
        data.processTag = processTag;
    },
    level: config.tracer.level,
    transport: function (data) {
        if (loggerWriteStream !== process.stdout) {
            process.stdout.write(data.output + "\n");
        }
        loggerWriteStream.write(data.output + "\n");
    }
});
```

```
Error:(44, 54) TS2345: Argument of type '{ format: (string | { error: string; })[]; dateformat: string; preprocess: (data: LogOutput) => v...' is not assignable to parameter of type 'LoggerConfig'.
  Types of property 'format' are incompatible.
    Type '(string | { error: string; })[]' is not assignable to type 'string'.
```
```
Error:(55, 14) TS2339: Property 'processTag' does not exist on type 'LogOutput'.
```
```
Error:(60, 39) TS2339: Property 'output' does not exist on type 'string'.
```
```
Error:(62, 38) TS2339: Property 'output' does not exist on type 'string'.
```

### PR DESCRIPTION
**Pull request by Diluka**
And this fix #85

### CODE REVIEW

**Comment by Diluka** [comment]
@baryon any question about this?

**Comment by baryon** [comment]
@Diluka I got a error on `dtslint`, could you help?
https://travis-ci.org/baryon/tracer/jobs/451810612

**Comment by Diluka** [comment]
confused about this error. lint says export is redundant. but the given link suggests to add export

EL PSY CONGROO

在 2018年11月7日，下午6:31，LI Long <notifications@github.com> 写道：

**Comment by Diluka** [comment]
without `export`, we can't import interfaces into our projects. I suggest export all interfaces.

**Comment by baryon** [comment]
OK, rollback and ignore dtslint

**Pull request merged**
